#! /bin/sh
nitrogen --restore
setxkbmap -layout us,ir -option 'grp:alt_shift_toggle'
pgrep -x sxhkd > /dev/null || sxhkd &
~/.config/polybar/launch.sh
picom &
xset b off
xrdb -merge ~/.Xresources
urxvtd &

bspc monitor -d 1 2 3 4 5 6 7 8 9 10 

bspc config border_width         0
bspc config window_gap         	 15

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

